package com.boredom.project_5_submission

object HeroesData {
    private val heroNames = arrayOf(
        "Abaddon",
        "Alchemist",
        "Axe",
        "Beast Master",
        "Brew Master",
        "Bristleback",
        "Centaur",
        "Chaos Knight",
        "Clockwerk",
        "Doom"
    )
    private val heroDetails = arrayOf(
        "Abaddon, the Lord of Avernus, is a melee strength hero known as one of the most versatile characters in Dota due to his rather low mana dependence, short spell cooldowns and a large number of viable item choices. His ability to help sustain his allies and himself plus his strong tower diving capacity give him solid lane presence. Many of his abilities offer a large sum of utility, which makes him a strong support hero. Mist Coil serves as both a single target nuke and heal that helps shift the sustainability of both allied and enemy heroes in a lane at his will, though sacrificing a portion of his own health. Aphotic Shield holds as one of the most useful abilities in the game, able to shield a target from some damage while also able to reflect said damage to a huge area. The most important aspect is how it is able to dispel many status effects such as slows and stuns. His other abilities allow him to become a mix between a semi-carry and tank. Abaddon's passive, Curse of Avernus, allows his attacks to not only slow down his enemy, but also increase the attack speed of any ally attacking the same target while also silencing the target after a set of attacks. With his ultimate, Borrowed Time, Abaddon is able to shift all non-HP-removal damage he receives into health. When not on cooldown, Borrowed Time may activate passively when his health falls under a certain threshold, even under the most dire situations. Due to his powerful spells and versatility, Abaddon is an excellent addition to any team.",
        "Razzil Darkbrew, the Alchemist, is a melee strength hero whose alchemical prowess makes him a strange but versatile fighter. He is an unusual carry based upon transmuting killed creeps into large amounts of bonus gold, with both an early game and late game presence due to the enormous health regeneration from his ultimate and the first strike nature of his other spells. His low but balanced attributes and the sure promise of gold for items means he can be one of the most disparately built heroes in the game. Unstable Concoction is his main contribution early on, dealing good damage and a lengthy stun. Acid Spray allows him to rapidly clear waves of creeps for his Greevil's Greed to contribute massive amounts of extra income. A well-equipped Alchemist can then use Chemical Rage to its fullest effect, as the incredible regeneration and base attack time reduction make it one of the best steroid abilities in the game.",
        "Mogul Khan, the Axe, is a melee strength hero, infamous for creating chaos in battle and thriving off of it. Axe is commonly played as an initiator, as his potent disables can disrupt the enemy's formation and give his team openings in fights. Axe's fighting style demands that he gets up close and very personal, as he can taunt enemies into attacking him with Berserker's Call, preventing them from engaging his teammates and granting him a huge amount of bonus armor. Once he has the enemy's attention, he can counter those who strike him with a sweeping Counter Helix that slashes all enemies at melee range with pure damage. He also has a slow and damage-over-time nuke in Battle Hunger, which can harass the enemy or force them to join in battle, while also slowing their movement speed and boosting his own. Finally, he has the ability to unconditionally remove weakened enemies from the battlefield if they are under a certain threshold with Culling Blade, while simultaneously boosting his allies' speed. A bloodthirsty and indomitable warrior, Axe's presence on the battlefield is felt by friend and foe alike, dominating the attention of the enemy wherever he goes.",
        "Karroch, the Beastmaster, is a versatile melee strength hero most commonly played as an offlaner and ganker who brings a good amount of utility to his team in any situation. His Wild Axes allows him to lane and farm quite effectively throughout the game, even when pressured. He is able to summon a hawk and boar to aid him, each providing a good amount of utility to his team. Hawks provide free flying vision around the map, scouting his enemies while his Boars can harass and slow his enemies to a crawl while aiding him in combat. His Inner Beast aura makes his team a force to be reckoned with, providing a hefty boost to attack speed to himself, his summons, and all nearby allies. Finally, his ultimate, Primal Roar, is the longest lasting single-target reliable stun in the game and also penetrates spell immunity (being only counterable by Linken's Sphere), providing a strong initiation for his team to claim a kill. With these skills, he can push enemy towers quickly and safely, take down undefended targets with the help of Necronomicon summons, lock down a single target, and also kite enemies in teamfights. With careful observation of the battlefield, Beastmaster takes down enemies one by one and paves the way to victory.",
        "Mangix, the Brewmaster, is a melee strength hero that can fill almost any role, though he is primarily seen as a carry, ganker, tank or initiator. He fits well into any lane, but is very experience dependent, which means he is often seen on the offlane or the midlane. His core abilities make him a respectable physical damage dealer and an especially good duelist since he has abilities that involve negating opposing attacks while strengthening his own. However, his true power lies in his ultimate, Primal Split, which, if used properly, can by itself turn the tide of a team fight. Each of the three aspects of the Brewmaster are exceptionally powerful, with exceptional disables, survivability against magic and physical attacks, and damage; they are also able to charge recklessly into the enemy since the damage they take is not permanent, and very rarely will all three die before Primal Split ends. For this reason, Brewmaster is almost always built to fully maximize the potential of this ultimate, getting items such as Blink Dagger so that he can combo into his ultimate without risk of being initiated on, Heart of Tarrasque to ensure he can survive the first wave of stuns and burst in order to cast his ultimate, and of course Aghanim's Scepter to give Brewmaster two charges of Primal Split and a possibility to cancel it at any time.",
        "Rigwarl, the Bristleback, is a melee strength hero famous for his array of synergistic, simplistic, and yet effective spells with low mana costs and cooldowns. Though each cast of his spells has relatively weak potency on its own, their instances have a cumulative effect, making the Bristleback quite deadly the longer he stays alive in a fight; this is directly reflected in his ultimate, Warpath, which powers up his movement and attack damage based on the number of spells he recently cast. He is able to increasingly slow his enemies down and reduce their armor with Viscous Nasal Goo and hit them with a barrage of Quill Sprays, making him an effective chaser when ganking enemies. His low strength gain makes him seem less tanky than most strength heroes at first glance, but his signature Bristleback passive substantially reduces all damage he takes from the sides and especially the rear, making him very difficult to bring down if he's facing away from his enemies. In the right hands, Bristleback is a powerful ganker in the early stages of the game, and a powerful hard carry in the later stages depending on how much farm he gets.",
        "Bradwarden, the Centaur Warrunner, is a melee strength hero whose natural place in combat is right in the center of battle. His abilities stop enemies around him in their tracks and inflict heavy damage, making him an excellent initiator. He is also a powerful tank, having the highest strength gain in the game.Bradwarden has immense natural health, and his skills' area of effect means that he can charge into combat and incapacitate groups of enemies at a time. Hoof Stomp and Double Edge make a great combo of stunning and burst damage on short cooldowns and his Retaliate means instant retaliation on enemies who try attack him, as well as his nearby allies with the proper late-game talent. His ultimate, Stampede effectively turns the entire team into initiators, granting them high speed and the ability to flatten enemies under as they pass over them.Although he is usually not played as a carry, he can scale powerfully with items, becoming a hard-hitting semi-carry that is nearly impossible to kill.",
        "Chaos Knight is a melee strength hero with one of the highest physical damage output ceilings of all heroes. He is mostly played as a carry and ganker. As his name implies, he has a theme based on randomness and uncertainty. His regular attack has an incredibly wide thirty damage spread, making his last hitting ability somewhat unreliable. Chaos Bolt is his most notorious luck-based ability which, at max level, can stun a target anywhere between a mediocre 2 seconds to an effective 4 seconds that will almost certainly assure the target's death; it will also deal a variable amount of damage ranging from minuscule to moderate. Reality Rift pulls Chaos Knight and his target to a predetermined point along the line between the two and reduces the foe's armor. Chaos Strike is a crit-based ability with a proc chance and has random damage values. The four illusions produced by his ultimate Phantasm, that can deal up to his full attack damage at max level, benefit from his Chaos Strike and can teleport alongside him to attack the target whenever he uses Reality Rift. This allows Chaos Knight's physical damage output to be multiplied by up to four during teamfights later in the game, and it is not uncommon to see enemy heroes being killed instantly after being Reality Rifted by the apocalyptic horsemen. Thus, Chaos Knight is played as a carry who excels in both the mid and late game, if the game drags on long enough and he is able to acquire enough strength-based and survivability items to ensure that his illusions can stay alive, he will be able to overpower most hard carries and potentially wipe out an entire team by himself.",
        "Rattletrap, the Clockwerk, is a melee strength hero known as being one of the most well-rounded initiator-gankers in the game. Rattletraps wide array of disables and nukes allows him to cause chaos among the enemy team and break up their formation, giving his team a powerful advantage in any fight. Battery Assault allows Clockwerk to inflict repeated damage ticks and mini-stuns on nearby enemies, allowing him to constantly hinder any enemies he manages to get close to and single out. He can also disrupt enemy movement and pen in foes with his Power Cogs, which induces an electric shock to foes outside, stunning them while damaging them and burning their mana, and can render enemies caught inside helpless. His damage nuke, Rocket Flare, gives him global nuking power that also provides scouting vision for him and his team. Finally, his ultimate, Hookshot, allows Rattletrap to instantaneously latch onto and stun a foe from long range, making him a very strong ganker. Few can escape Clockwerk once he has his sights locked in, and his machinations make him a powerful ally to have on any team.",
        "Lucifer, the Doom, is a melee strength hero with strong farming capabilities, good versatility, and one of the strongest single-target disables in the game. His very low starting armor makes him vulnerable to harassment, but his abilities and high health allow him to lane or even jungle quite effectively. A ruthless demon, Doom possesses malicious abilities revolving around greed, fire, and death. His Devour ability allows him to consume creeps, providing additional gold and allowing him to absorb their powers, using them to increase his own strength. Because there are numerous neutral creep abilities to choose from to supplement his other abilities, the role that he chooses to play is quite flexible. Scorched Earth allows him to chase or escape effectively, all while slowly burning his enemies. He can deal tremendous damage with Infernal Blade, an attack modifier which mini-stuns enemies and deals damage over time, based on their maximum health, making it a powerful nuking ability that scales into the late game. Finally, his namesake ultimate Doom serves as one of the strongest single-target lockdown abilities in the game. A unit afflicted with Doom takes intense damage over a lengthy duration while having all its active abilities - even those from items - completely silenced. With numerous expensive items in his arsenal and a key enemy hero rendered useless for a teamfight, a farmed Doom ensures that nobody can extinguish his flame."
    )

    private val heroImages = intArrayOf(
        R.drawable.abaddon_one,
        R.drawable.alchemist_one,
        R.drawable.axe_one,
        R.drawable.beast_master_one,
        R.drawable.brew_master_one,
        R.drawable.bristleback_one,
        R.drawable.centaur_warrunner_one,
        R.drawable.chaos_knight_one,
        R.drawable.clockwerk_one,
        R.drawable.doom_lucifer_one
    )

    val listData: ArrayList<DotaHero> get(){
    val list = arrayListOf<DotaHero>()
        for(position in heroNames.indices){
            val hero = DotaHero()
            hero.name = heroNames[position]
            hero.detail = heroDetails[position]
            hero.photo = heroImages[position]
            list.add(hero)
        }
        return list
    }
}